fix route name

diff --git a/.github/workflows/pokerEventScheduler.yml b/.github/workflows/pokerEventScheduler.yml
--- a/.github/workflows/pokerEventScheduler.yml
+++ b/.github/workflows/pokerEventScheduler.yml
@@ -30,3 +30,27 @@ jobs:
             echo "Request failed"
             exit 1
           fi
+
+      - name: Update caches
+        run: |
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
+            -X POST \
+            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
+            https://api.johnfoxweb.com/api/admin/updatecaches)
+          echo "Status code: $STATUS_CODE"
+          if [ "$STATUS_CODE" -ne 200 ]; then
+            echo "Request failed"
+            exit 1
+          fi
+
+      - name: Check name clashes
+        run: |
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
+            -X POST \
+            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
+            https://api.johnfoxweb.com/api/admin/checknameclashes)
+          echo "Status code: $STATUS_CODE"
+          if [ "$STATUS_CODE" -ne 200 ]; then
+            echo "Request failed"
+            exit 1
+          fi
